import { mkdir, readFile, writeFile, copyFile, symlink } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { GENERATED_DIR, PROJECTS_DIR, ROOT_DIR } from "../config.js";
import type { Project } from "../types.js";

const RUNTIME_TEMPLATE = join(
  ROOT_DIR,
  "backend",
  "src",
  "generator",
  "runtime.template.mjs"
);

function slugify(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "mcp-server"
  );
}

async function ensureDependencyLink(): Promise<void> {
  const linkPath = join(GENERATED_DIR, "node_modules");
  if (existsSync(linkPath)) return;
  const target = join(ROOT_DIR, "backend", "node_modules");
  try {
    // "junction" works on Windows without admin rights; "dir" elsewhere.
    await symlink(target, linkPath, process.platform === "win32" ? "junction" : "dir");
  } catch {
    // If linking fails the user can still `npm install` inside generated/.
  }
}

export interface GenerateResult {
  serverPath: string;
  generatedDir: string;
  serverName: string;
}

/**
 * Generates a standalone, self-contained MCP server (stdio transport) from a
 * project definition. The user never sees this code — it is a build artifact.
 */
export async function generateServer(
  project: Project,
  projectId: string
): Promise<GenerateResult> {
  await mkdir(GENERATED_DIR, { recursive: true });

  const serverName = slugify(project.name);
  const runtime = await readFile(RUNTIME_TEMPLATE, "utf-8");

  const header = [
    `// Generated by MyMCP on ${new Date().toISOString()}`,
    `const SERVER_NAME = ${JSON.stringify(serverName)};`,
    `const TOOLS = ${JSON.stringify(project.tools, null, 2)};`,
    `const INTEGRATIONS = ${JSON.stringify(project.integrations, null, 2)};`,
    "",
  ].join("\n");

  const serverPath = join(GENERATED_DIR, "server.mjs");
  await writeFile(serverPath, header + runtime, "utf-8");

  // The generated ESM server needs @modelcontextprotocol/sdk + zod at runtime.
  // ESM ignores NODE_PATH, so we link generated/node_modules to the already
  // installed backend/node_modules. This lets both our "Start" button and a
  // directly-launched client (Claude Desktop, Cursor) run the server without
  // the non-technical user ever running `npm install`.
  await ensureDependencyLink();

  // A package.json so the standalone export `npm install && node server.mjs` works.
  const pkg = {
    name: serverName,
    version: "1.0.0",
    private: true,
    type: "module",
    bin: { [serverName]: "server.mjs" },
    dependencies: {
      "@modelcontextprotocol/sdk": "^1.12.0",
      zod: "^3.24.1",
    },
  };
  await writeFile(
    join(GENERATED_DIR, "package.json"),
    JSON.stringify(pkg, null, 2),
    "utf-8"
  );

  // Keep a copy of the source project alongside the artifact.
  const sourceProject = join(PROJECTS_DIR, projectId, "project.json");
  if (existsSync(sourceProject)) {
    await copyFile(sourceProject, join(GENERATED_DIR, "project.json"));
  }

  await writeFile(
    join(GENERATED_DIR, "README.md"),
    [
      `# ${project.name}`,
      "",
      project.description,
      "",
      "## Run this MCP server",
      "",
      "```bash",
      "npm install",
      "node server.mjs",
      "```",
      "",
      "This server speaks MCP over stdio. Connect it to Claude Desktop, Cursor,",
      "VS Code or any MCP client using the config from the Export screen.",
      "",
    ].join("\n"),
    "utf-8"
  );

  return { serverPath, generatedDir: GENERATED_DIR, serverName };
}
